FROM python:3.6-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /app

COPY . /app

RUN chmod +x /app/entrypoint.sh
RUN pip install --no-cache-dir cryptography==2.1.4
RUN  pip install --no-cache-dir -r /app/requirements.txt 
WORKDIR /app

EXPOSE 8080

ENTRYPOINT ["/app/entrypoint.sh"]