# Generated by Django 3.0.6 on 2020-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0003_auto_20200521_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=128),
        ),
    ]
